In [ ]:
# Ejemplo de lista
lista = [1, 2, 3, 4, 5]
# Descripción: Una lista es una colección ordenada y mutable de elementos. 
# En este caso, la lista contiene los números del 1 al 5.

# Ejemplo de tupla
tupla = (1, 2, 3, 4, 5)
# Descripción: Una tupla es similar a una lista, pero es inmutable, lo que significa que
# no se pueden modificar sus elementos una vez creada. Aquí, la tupla contiene los números del 1 al 5.

# Ejemplo de diccionario
diccionario = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
# Descripción: Un diccionario es una colección de pares clave-valor.
# En este caso, las claves son letras ('a', 'b', 'c', 'd', 'e') y los valores son los números del 1 al 5.

# Ejemplo de conjunto o set
conjunto = {1, 2, 3, 4, 5}
# Descripción: Un conjunto es una colección no ordenada y sin elementos duplicados. 
# Aquí, el conjunto contiene los números del 1 al 5.



In [1]:
import numpy as np

try:
    np.version.version
    print("NumPy está instalado. Versión:", np.version.version)
except ImportError:
    print("NumPy no está instalado.")
import numpy 

NumPy está instalado. Versión: 1.24.2


In [2]:
# los np arrays  pueden ser en tres d
# 1d vectores
# 2d matriz
# 3d tensores
# cracion de arreglos 

# aca le paso el rango que quiero
npa= np.array(range(10))
npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# agregar nuevo valor 
valor=85
# al array previamente nombrado le asigno np.append(pasando como argumento el array mas el nuevo valor)
npa=np.append(npa,valor) 
print(npa)

[ 0  1  2  3  4  5  6  7  8  9 85]


In [6]:
# eliminar por posicion 
index_eliminar=5
npa=np.delete(npa,index_eliminar)
print(npa)

[ 0  1  2  3  4  6  7  8  9 85]


In [7]:
# creo un array con 10 numeros iguales por defecto son float
np_ceros=np.zeros(10)
print(np_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
# aca le aclaro que sean enteros
np_ceros_int=np.zeros(10,dtype=int)
print(np_ceros_int)

[0 0 0 0 0 0 0 0 0 0]


In [10]:
np_uno=np.ones(10)
print(np_uno)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
# genero un arreglo por tamaño y valor
np_relleno=np.full(10,256)
print(np_relleno)

[256 256 256 256 256 256 256 256 256 256]


In [13]:
np_arreglo=np.array(range(10))
print(np_arreglo)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
np_arreglo=np.arange(10.0) # parecido al range, nada mas que aca tiene flotante
print(np_arreglo)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [18]:
# igual que el range
np_rango=np.arange(10)
np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np_rango=np.arange(5,25,5)
np_rango

array([ 5, 10, 15, 20])

In [17]:
#nd arrays con valores aleatorios y de dos dimensiones
# creo un arreglo  que los numeros sean de 0 a 10 sin incluir, que sean 4 columnas de tres valores cada una.
# el randon es para aleatorios
np_random_dimensiones=np.random.randint(10,size=(3,4))
np_random_dimensiones


array([[5, 4, 1, 0],
       [5, 5, 4, 5],
       [7, 3, 6, 3]])

In [26]:
#Propiedades de los arrays
np_random_dimensiones.ndim # dimensiones
np_random_dimensiones.shape #filas y columnas
np_random_dimensiones.size # tamaño (filas* columnas)
np_random_dimensiones.max() # devuelve el max
np_random_dimensiones.min() # devuelve el min

0

In [27]:
# devuelve una copia unidimensinal
np_random_dimensiones.flatten()

array([5, 4, 1, 0, 5, 5, 4, 5, 7, 3, 6, 3])

In [28]:
# me sirve para ver los tipos de datos de los arreglos
print(np_random_dimensiones.dtype)

int32


In [29]:
import numpy as np

# Tipo de dato int (entero)
arr_int = np.array([1, 2, 3])
print("Tipo de dato int:", arr_int.dtype)  # int64

# Tipo de dato float (punto flotante)
arr_float = np.array([1.0, 2.5, 3.7])
print("Tipo de dato float:", arr_float.dtype)  # float64

# Tipo de dato bool (booleano)
arr_bool = np.array([True, False, True])
print("Tipo de dato bool:", arr_bool.dtype)  # bool

# Tipo de dato str (cadena de texto)
arr_str = np.array(['hola', 'mundo'])
print("Tipo de dato str:", arr_str.dtype)  # <U5 (cadena de caracteres de longitud máxima 5)

# Tipo de dato object (objeto genérico)
arr_obj = np.array([1, 'dos', True])
print("Tipo de dato object:", arr_obj.dtype)  # object

# Tipo de dato complex (número complejo)
arr_complex = np.array([2 + 3j, 4 - 1j])
print("Tipo de dato complex:", arr_complex.dtype)  # complex128 (números complejos de 128 bits)

import numpy as np

# Tipo de dato int (entero)
arr_int = np.array([1, 2, 3])
print("Tipo de dato int:", arr_int.dtype)  # int64

# Tipos de datos de enteros de tamaño fijo
arr_int8 = np.array([1, 2, 3], dtype=np.int8)
print("Tipo de dato int8:", arr_int8.dtype)  # int8

arr_int16 = np.array([1, 2, 3], dtype=np.int16)
print("Tipo de dato int16:", arr_int16.dtype)  # int16

arr_int32 = np.array([1, 2, 3], dtype=np.int32)
print("Tipo de dato int32:", arr_int32.dtype)  # int32

arr_int64 = np.array([1, 2, 3], dtype=np.int64)
print("Tipo de dato int64:", arr_int64.dtype)  # int64
import numpy as np

# Tipo de dato uint (entero sin signo)
arr_uint = np.array([1, 2, 3], dtype=np.uint)
print("Tipo de dato uint:", arr_uint.dtype)  # uint64

# Tipo de dato float de precisión reducida
arr_float16 = np.array([1.0, 2.5, 3.7], dtype=np.float16)
print("Tipo de dato float16:", arr_float16.dtype)  # float16

arr_float32 = np.array([1.0, 2.5, 3.7], dtype=np.float32)
print("Tipo de dato float32:", arr_float32.dtype)  # float32

# Tipo de dato complex de precisión reducida
arr_complex64 = np.array([2 + 3j, 4 - 1j], dtype=np.complex64)
print("Tipo de dato complex64:", arr_complex64.dtype)  # complex64

# Tipo de dato booleano de precisión reducida
arr_bool8 = np.array([True, False, True], dtype=np.bool8)
print("Tipo de dato bool8:", arr_bool8.dtype)  # bool8


Tipo de dato int: int32
Tipo de dato float: float64
Tipo de dato bool: bool
Tipo de dato str: <U5
Tipo de dato object: <U11
Tipo de dato complex: complex128
Tipo de dato int: int32
Tipo de dato int8: int8
Tipo de dato int16: int16
Tipo de dato int32: int32
Tipo de dato int64: int64
Tipo de dato uint: uint32
Tipo de dato float16: float16
Tipo de dato float32: float32
Tipo de dato complex64: complex64
Tipo de dato bool8: bool


C:\Users\Usuario\AppData\Local\Temp\ipykernel_19580\2459202723.py:63: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  arr_bool8 = np.array([True, False, True], dtype=np.bool8)


In [30]:
np_random_dimensiones.dtype


dtype('int32')

In [31]:
# uno es el tamaño de cada elemento, otro el tamaño del arreglo
arr = np.array([1, 2, 3, 4, 5])
print("Tamaño de cada elemento (itemsize):", arr.itemsize)  # 8 bytes (para enteros de 64 bits)
print("Tamaño total en bytes (nbytes):", arr.nbytes)  # 40 bytes (5 elementos * 8 bytes por elemento)


Tamaño de cada elemento (itemsize): 4
Tamaño total en bytes (nbytes): 20


In [32]:
import numpy as np

# Crear un arreglo de enteros utilizando int32
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
print("Arreglo de enteros int32:")
print(arr_int32)
print("Tipo de datos:", arr_int32.dtype)
print("Tamaño en bytes:", arr_int32.itemsize)

# Crear un arreglo de enteros utilizando int64
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
print("\nArreglo de enteros int64:")
print(arr_int64)
print("Tipo de datos:", arr_int64.dtype)
print("Tamaño en bytes:", arr_int64.itemsize)

# Crear un arreglo de números de coma flotante utilizando float32
arr_float32 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print("\nArreglo de números de coma flotante float32:")
print(arr_float32)
print("Tipo de datos:", arr_float32.dtype)
print("Tamaño en bytes:", arr_float32.itemsize)

# Crear un arreglo de números de coma flotante utilizando float64
arr_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print("\nArreglo de números de coma flotante float64:")
print(arr_float64)
print("Tipo de datos:", arr_float64.dtype)
print("Tamaño en bytes:", arr_float64.itemsize)


Arreglo de enteros int32:
[1 2 3]
Tipo de datos: int32
Tamaño en bytes: 4

Arreglo de enteros int64:
[1 2 3]
Tipo de datos: int64
Tamaño en bytes: 8

Arreglo de números de coma flotante float32:
[1. 2. 3.]
Tipo de datos: float32
Tamaño en bytes: 4

Arreglo de números de coma flotante float64:
[1. 2. 3.]
Tipo de datos: float64
Tamaño en bytes: 8


In [33]:
# INDEXADO Y ACCESO

rango= range(1,11)
np_numeros=np.array(rango)
np_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
#acceso por indice
np_numeros[3]
# si pongo el -1 arranca por el ultimo y asi sucesivamente
 
np_numeros[-1]

10

In [39]:
# desde 0 a 3-1
np_numeros[:3]
# desde indice cero a 8 con paso2
# seria slicing
np_numeros[:8:]
np_numeros[-5::] # los cinco ultimo ()

array([ 6,  7,  8,  9, 10])

In [41]:
#Arrays 3d 3 matrices de 3*4
np_3d=np.random.randint(10, size=(3,3,4))
np_3d

array([[[1, 2, 2, 8],
        [6, 5, 6, 2],
        [0, 8, 8, 9]],

       [[3, 1, 5, 9],
        [3, 5, 1, 8],
        [0, 7, 3, 4]],

       [[2, 1, 8, 3],
        [5, 4, 0, 5],
        [0, 9, 0, 4]]])

In [45]:
np_3d[1,1,1]
print(np_3d[1,1,1])

5


In [46]:
np_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np_numeros[0:5]  # es = a np_numeros[:5] 

array([1, 2, 3, 4, 5])

In [58]:
import numpy as np
#reshape
#La función reshape es una operación que se utiliza en numpy para cambiar la forma (shape)
# de un arreglo multidimensional sin alterar los datos contenidos en él. Permite reorganizar los elementos 
# del arreglo en una nueva estructura especificada por las dimensiones deseadas.
#Ejemplo
# la ajederez tiene 8 *8 , la matriz de abajo da 64 (1*(65-1)) el reshape lo que hace es hacerlo 8*8

np.arange(65)
# ojo siempre tiene que ser del mismo tamaño 
ajedrez=np.arange(1,65).reshape(8,8)
ajedrez

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [60]:
ar1=np.random.randint(1000,size=8)
ar2=np.random.randint(1000,size=8)
ar3=np.random.randint(1000,size=8)
print(ar1)
print(ar2)
print(ar3)

[547 477 770 881  15 365 706 325]
[992 938 482 680 679 871  25 629]
[514  47 810 863 398  75 767 360]


In [61]:
#Concatenacion de arreglos con concate los hace uno al lado del otro
array_concatenados=np.concatenate([ar1,ar2,ar3])
array_concatenados

array([547, 477, 770, 881,  15, 365, 706, 325, 992, 938, 482, 680, 679,
       871,  25, 629, 514,  47, 810, 863, 398,  75, 767, 360])

In [63]:
# apilados vertical u horizontal 
#array_apilados=np.vstack([ar1,ar2,ar3])
array_apilados=np.hstack([ar1,ar2,ar3])
array_apilados

array([547, 477, 770, 881,  15, 365, 706, 325, 992, 938, 482, 680, 679,
       871,  25, 629, 514,  47, 810, 863, 398,  75, 767, 360])

In [64]:
array_concatenados=np.concatenate([ar1,ar2,ar3],axis=0)# cero concatena por filas 
# array_concatenados=np.concatenate([ar1,ar2,ar3],axis=1)# cero concatena por columnas 
array_concatenados

array([547, 477, 770, 881,  15, 365, 706, 325, 992, 938, 482, 680, 679,
       871,  25, 629, 514,  47, 810, 863, 398,  75, 767, 360])

In [77]:
array_concatenados
#a un nuevo array le asigno split, el cual le paso como parametro un arreglo y el indice donde los divide
# del 0 posicion -1 un arreglo, de la posicion al final otro arreglo da como resultado
array_partido=np.split(array_concatenados,[6])
array_partido

[array([547, 477, 770, 881,  15, 365]),
 array([706, 325, 992, 938, 482, 680, 679, 871,  25, 629, 514,  47, 810,
        863, 398,  75, 767, 360])]

In [4]:
#Operaciones vectorizadas
import numpy as np
array_aleatorios=np.random.randint(1000,size=100000000)
array_aleatorios

array([706, 614,  48, ..., 999, 455, 581])

In [79]:
# tamaño del array
len(array_aleatorios)

100000000

In [11]:
import pandas as pd
import numpy as np
import time
#operaciones 

#Promedios de eleemtnos del arreglos

%%time
suma=0
for i in array_aleatorios:
    suma+=i
promedio=suma/len(array_aleatorios)
print(promedio)

UsageError: Line magic function `%%time` not found.


In [13]:
%%time
array_aleatorios.mean()

CPU times: total: 156 ms
Wall time: 147 ms


499.57524388

In [15]:
# las operaciones vectorizadas son mucho mejor, porque se optimiza el tiempo, antes que hacerlo con un ciclo FOR
#array_aleatorios.min() MINIMO
#array_aleatorios.max() maximo
#array_aleatorios.sum() suma
#np.median(array_aleatorios) mediana
#np.std(array_aleatorios)desviacion
np.var(array_aleatorios) #varianza

83336.02423905837